package error

import (
	"errors"
)

var (
	InvalidToken             = errors.New(invalidToken)
	InvalidBillingId         = errors.New(invalidBillingId)
	HeaderDetailAlreadExist  = errors.New(headerDetailAlreadExist)
	HeaderAlreadExist        = errors.New(headerAlreadyExist)
	InvalidPipelineData      = errors.New(invalidPipelineData)
	CannotChargeCredit       = errors.New(cannotChargeCredit)
	InvalidId                = errors.New(invalidId)
	NoDefaultdata            = errors.New(noDefaultdata)
	EmpyPipelineStatus       = errors.New(emptyPipelineStatus)
	InvalidPipelineStatus    = errors.New(invalidPipelineStatus)
	InvalidPipelineId        = errors.New(invalidPipelineId)
	UnknownError             = errors.New(unknownError)
	OrderNumberAlreadyExist  = errors.New(orderNumberAlreadyExist)
	AccountOverDue           = errors.New(accountOverDue)
	EmptyPipelineStatus      = errors.New(emptyPipelineStatus)
	EmailAreadyExist         = errors.New(emailAreadyExist)
	InvalidUserId            = errors.New(invalidUserId)
	EmailDoesNotExist        = errors.New(emailDoesNotExist)
	InvalidOrderNumber       = errors.New(invalidOrderNumber)
	TokenAlreadyUsed         = errors.New(tokenAlreadyUsed)
	TokenExpired             = errors.New(tokenExpired)
	InvalidPassword          = errors.New(invalidPassword)
	DecodeError              = errors.New(decodeError)
	NoRecordUpdate           = errors.New(noRecordUpdate)
	DbError                  = errors.New(dbError)
	InvalidDateFrom          = errors.New(invalidDateFrom)
	InvalidDateTo            = errors.New(invalidDateTo)
	InvalidDate              = errors.New(invalidDate)
	InvalidClientId          = errors.New(invalidClientId)
	InvalidDueDate           = errors.New(invalidDueDate)
	InvalidCreatorId         = errors.New(invalidCreatorId)
	MaxOrderLimit            = errors.New(maxOrderLimit)
	PipelineStateError       = errors.New(pipelineStateError)
	InvalidTurnAroundTime    = errors.New(invalidTurnAroundTime)
	CannotProcessPipeline    = errors.New(cannotProcessPipeline)
	InvalidTurboLoad         = errors.New(invalidTurboLoad)
	InvalidTurboLoadModerate = errors.New(invalidTurboLoadModerate)
	InvalidTurboLoadBusy     = errors.New(invalidTurboLoadBusy)
	InvalidQcID              = errors.New(invalidQcID)
	OpenSessionExist         = errors.New(openSessionExist)
	InvalidInvoiceDate       = errors.New(invalidInvoiceDate)
	InvalidStartDate         = errors.New(invalidStartDate)
	InvalidEndDate           = errors.New(invalidEndDate)
	RoleIsEmpty              = errors.New(roleIsEmpty)
)
